# Generated by Django 5.0.4 on 2024-07-17 09:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.PositiveIntegerField()),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Bancos',
                'ordering': ('cod',),
            },
        ),
        migrations.CreateModel(
            name='OrganizacaoCaptadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('titular_conta', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Nome do titular deve conter apenas letras e espaços', regex='^[a-zA-Z ]+$')])),
                ('numero_conta', models.PositiveIntegerField()),
                ('agencia_bancaria', models.PositiveIntegerField()),
                ('cpf_cnpj', models.CharField(max_length=20)),
                ('contato', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizacoes', to='organizacoes.banco')),
            ],
        ),
    ]
