# Generated by Django 5.0.4 on 2024-07-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('meta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('arrecadacao_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modo', models.CharField(blank=True, choices=[('ACESSO_IMEDIATO', 'Acesso Imediato'), ('TUDO_OU_NADA', 'Tudo ou Nada')], max_length=20, null=True)),
                ('em_andamento', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_4', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_5', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_juros', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentagem_colaborador', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentagem_organizacao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('prazo_retorno', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_1', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_1', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao_1', models.TextField(blank=True, null=True)),
                ('valor_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nome_2', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_2', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao_2', models.TextField(blank=True, null=True)),
                ('valor_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nome_3', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_3', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao_3', models.TextField(blank=True, null=True)),
                ('valor_3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nome_4', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_4', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao_4', models.TextField(blank=True, null=True)),
                ('valor_4', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nome_5', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_5', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao_5', models.TextField(blank=True, null=True)),
                ('valor_5', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCrowdfunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DOACAO', 'Doação'), ('RECOMPENSA', 'Recompensa'), ('EMPRESTIMO', 'Empréstimo')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ValorSugerido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
