# Generated by Django 5.0.4 on 2024-07-17 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campanhas', '0001_initial'),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campanhas', to='projetos.projeto'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='campanha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to='campanhas.campanha'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='campanha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimo', to='campanhas.campanha'),
        ),
        migrations.AddField(
            model_name='recompensa',
            name='campanha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recompensa', to='campanhas.campanha'),
        ),
        migrations.AddField(
            model_name='campanha',
            name='tipo_crowdfunding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanhas', to='campanhas.tipocrowdfunding'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='valores_sugeridos',
            field=models.ManyToManyField(to='campanhas.valorsugerido'),
        ),
    ]
