# Generated by Django 5.0.4 on 2024-07-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='valores_sugeridos',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='valor_sugerido_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='valor_sugerido_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='valor_sugerido_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='valor_sugerido_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='ValorSugerido',
        ),
    ]
