# Generated by Django 5.0.4 on 2024-07-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembroProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(choices=[('MEMBRO', 'Membro'), ('ADMINISTRADOR', 'Administrador')], default='MEMBRO', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=255)),
                ('imagem_perfil', models.ImageField(default='default_projeto.jpg', upload_to='projeto_imagens/')),
                ('texto', models.TextField(default='', max_length=5000)),
                ('imagem1', models.ImageField(blank=True, null=True, upload_to='imagens_pitch_deck/')),
                ('imagem2', models.ImageField(blank=True, null=True, upload_to='imagens_pitch_deck/')),
                ('imagem3', models.ImageField(blank=True, null=True, upload_to='imagens_pitch_deck/')),
                ('data_criacao', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
