# Generated by Django 5.0.4 on 2024-07-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membroprojeto',
            name='data_inclusao',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
