# Generated by Django 5.0.4 on 2024-07-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_membroprojeto_data_inclusao'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='tem_campanha',
            field=models.BooleanField(default=False),
        ),
    ]
