# Generated by Django 5.0.4 on 2024-07-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='organizacao_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
