# Generated by Django 5.0.4 on 2024-07-17 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campanhas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContribuicaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_contribuicao', models.DateTimeField(auto_now_add=True)),
                ('informacoes_contribuicao', models.TextField()),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribuicoes', to='campanhas.campanha')),
            ],
        ),
    ]
