# Generated by Django 5.0.4 on 2024-07-17 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0002_initial'),
        ('contribuicoes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribuicaofinanceira',
            name='informacoes_contribuicao',
        ),
        migrations.RemoveField(
            model_name='contribuicaofinanceira',
            name='valor',
        ),
        migrations.AddField(
            model_name='contribuicaofinanceira',
            name='crowd_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contribuicaofinanceira',
            name='detalhe_contribuicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribuicoes', to='campanhas.recompensa'),
        ),
        migrations.AddField(
            model_name='contribuicaofinanceira',
            name='tipo_crowd',
            field=models.CharField(blank=True, choices=[('DOACAO', 'Doação'), ('RECOMPENSA', 'Recompensa'), ('EMPRESTIMO', 'Empréstimo')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contribuicaofinanceira',
            name='valor_contribuicao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
