# Generated by Django 5.0.4 on 2024-07-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribuicoes', '0003_remove_contribuicaofinanceira_informacoes_contribuicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribuicaofinanceira',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contribuicaofinanceira',
            name='cvv_cartao',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='contribuicaofinanceira',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('CARTAO', 'Cartão de Crédito/Débito'), ('PIX', 'Pix')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contribuicaofinanceira',
            name='nome_titular',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contribuicaofinanceira',
            name='numero_cartao',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='contribuicaofinanceira',
            name='validade_cartao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
