# Generated by Django 5.0.4 on 2024-07-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribuicoes', '0004_contribuicaofinanceira_chave_pix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribuicaofinanceira',
            name='status_contrib',
            field=models.CharField(choices=[('Ativa', 'Ativa'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], default='Ativa', max_length=20),
        ),
    ]
