# Generated by Django 5.0.4 on 2024-07-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribuicoes', '0005_contribuicaofinanceira_status_contrib'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivosCancelamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('CIRCUNSTANCIAS', 'Mudanças de Circunstâncias Pessoais'), ('GESTAO', 'Descontentamento com a Gestão da Campanha'), ('INFORMACOES', 'Informações Enganosas ou Falsas'), ('ATRASOS', 'Atrasos ou Falta de Progresso'), ('PREFERENCIA', 'Preferência por Outra Campanha')], max_length=50)),
            ],
        ),
    ]
